spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2_db_files/loginPrj
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  #OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 332607151057-5kifr6ct5r3re0d9i09qhsv47n6pf38a.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
          kakao:
            client-id: 526b5c4963c4ff3e5d8c830964f98d01
            redirectUri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email, gender, profile_nickname
            client-name: Kakao
          naver:
            client-id: aCmlA8QLsgiNLgKxnHX4
            client-secret: Ytt21npLf5
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, gender, mobile
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

app:
  auth:
    tokenSecret: dfa07889d2651d1786427376c6c270b82976e2e0ba8f9f0a7c62f68a02943fe21a99e8cbd48aff8a63951bc06e2b809b9e8d5b81c8f8eaac5d12b71388b95903
    tokenExpiration: 1800000
  oauth2:
    redirectUri : "http://localhost:8080/oauth2/redirect"
